In [1]:
import pandas as pd

In [2]:
import psycopg2
conn=psycopg2.connect(
    host="localhost",
    database="brazilian e-commerce DB",
    user="postgres",
    password="your password"
)
cursor=conn.cursor()

# Load dataset from pstgreSQL

### order_level table

In [3]:
from sqlalchemy import create_engine

In [4]:
engine=create_engine("postgresql+psycopg2://postgres:yourpasswordlocalhost:5432/brazilian e-commerce DB")

In [5]:
query='''select 
i.order_id,
i.order_item_id,
i.price,
o.customer_id,
o.order_status,
o.order_purchase_timestamp,
o.order_delivered_customer_date,
o.order_estimated_delivery_date,
p.product_id,
p.product_category
from order_item i
left join orders o on i.order_id= o.order_id
left join products p on i.product_id=p.product_id
'''

In [6]:
orderlevel= pd.read_sql_query('''select 
i.order_id,
i.order_item_id,
i.price,
o.customer_id,
o.order_status,
o.order_purchase_timestamp,
o.order_delivered_customer_date,
o.order_estimated_delivery_date,
p.product_id,
p.product_category
from order_item i
left join orders o on i.order_id= o.order_id
left join products p on i.product_id=p.product_id

''',engine)
display(orderlevel)

,order_id,order_item_id,price,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,product_id,product_category
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:00,2017-09-20 23:43:00,2017-09-29,4244733e06e7ecb4970a6e2683c13e61,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:00,2017-05-12 16:04:00,2017-05-15,e5f2d52b802189ee658865ca93d83a8f,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,199.00,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:00,2018-01-22 13:19:00,2018-02-05,c777355d18b72b67abbeef9df44fd0fd,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:00,2018-08-14 13:32:00,2018-08-20,7634da152a4610f1595efa32f14722fc,perfumery
4,00048cc3ae777c65dbb7d2a0634bc1ea,1,21.90,816cbea969fe5b689b39cfc97a506742,delivered,2017-05-15 21:42:00,2017-05-22 13:44:00,2017-06-06,ef92defde845ab8450f9d70c526ef70f,housewares
...,...,...,...,...,...,...,...,...,...,...
112645,fff6889749958e42b47a7977a4cf0ea0,1,92.00,c5d108ecadaedf367e995520d36c9b1d,delivered,2017-09-25 22:41:00,2017-09-28 22:38:00,2017-10-10,75f6a4f019ec1322758d53b2fee2cc12,luggage_accessories
112646,fff6b8ca971f8e3ec822e99d0f2d3d21,1,199.00,2aec499f94f5e82786629a84b816ffb9,delivered,2017-09-15 11:44:00,2017-09-21 19:34:00,2017-10-04,9afaad66aca8b0c79e4f084a89c9c92b,telephony
112647,fff8287bbae429a99bb7e8c21d151c41,1,180.00,6c1e92a209dbf868706caa831090941e,delivered,2018-03-17 12:11:00,2018-04-07 10:07:00,2018-04-19,bee2e070c39f3dd2f6883a17a5f0da45,computers_accessories
112648,fff8287bbae429a99bb7e8c21d151c41,2,180.00,6c1e92a209dbf868706caa831090941e,delivered,2018-03-17 12:11:00,2018-04-07 10:07:00,2018-04-19,bee2e070c39f3dd2f6883a17a5f0da45,computers_accessories
112649,fffa82886406ccf10c7b4e35c4ff2788,1,229.90,a5201e1a6d71a8d21e869151bd5b4085,delivered,2017-12-18 16:33:00,2018-01-08 18:23:00,2018-01-24,bbe7651fef80287a816ead73f065fc4b,sports_leisure

In [7]:
orderlevel['order_id'].unique()

array(['00010242fe8c5a6d1ba2dd792cb16214',
       '00018f77f2f0320c557190d7a144bdd3',
       '000229ec398224ef6ca0657da4fc703e', ...,
       'fff6b8ca971f8e3ec822e99d0f2d3d21',
       'fff8287bbae429a99bb7e8c21d151c41',
       'fffa82886406ccf10c7b4e35c4ff2788'], dtype=object)

In [8]:
orderlevel.isnull().sum()

order_id                            0
order_item_id                       0
price                               0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_delivered_customer_date    2454
order_estimated_delivery_date       0
product_id                          0
product_category                 1627
dtype: int64

In [9]:
orderlevel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 10 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   price                          112650 non-null  float64
 3   customer_id                    112650 non-null  object
 4   order_status                   112650 non-null  object
 5   order_purchase_timestamp       112650 non-null  datetime64[ns]
 6   order_delivered_customer_date  110196 non-null  datetime64[ns]
 7   order_estimated_delivery_date  112650 non-null  datetime64[ns]
 8   product_id                     112650 non-null  object
 9   product_category               111023 non-null  object
dtypes: datetime64[ns](3), float64(1), int64(1), object(5)
memory usage: 8.6+ MB

# Null handling and rename column name

In [10]:
orderlevel.rename(columns={'order_purchase_timestamp':'order_date',
                           'order_delivered_customer_date':'delivery_date',
                          'order_estimated_delivery_date':'estimated_delivery_date'},inplace=True)

In [11]:
orderlevel['order_date']=pd.to_datetime(orderlevel['order_date'])

In [12]:
for col in ['order_status','product_category']:
 print(orderlevel[col].value_counts())

order_status
delivered      110197
shipped          1185
canceled          542
invoiced          359
processing        357
unavailable         7
approved            3
Name: count, dtype: int64
product_category
bed_bath_table               11115
health_beauty                 9670
sports_leisure                8641
furniture_decor               8334
computers_accessories         7827
                             ...
arts_and_craftmanship           24
la_cuisine                      14
cds_dvds_musicals               14
fashion_childrens_clothes        8
security_and_services            2
Name: count, Length: 71, dtype: int64

In [13]:
orderlevel.groupby('order_status')['order_status'].value_counts()

order_status
approved            3
canceled          542
delivered      110197
invoiced          359
processing        357
shipped          1185
unavailable         7
Name: count, dtype: int64

In [14]:
orderlevel['delivery_date']=orderlevel['delivery_date'].fillna(orderlevel['estimated_delivery_date'])
orderlevel['product_category']=orderlevel['product_category'].fillna('unknown')

In [15]:
orderlevel.isnull().sum()

order_id                   0
order_item_id              0
price                      0
customer_id                0
order_status               0
order_date                 0
delivery_date              0
estimated_delivery_date    0
product_id                 0
product_category           0
dtype: int64

## identify duplicates

In [16]:
orderlevel[orderlevel.duplicated()]

Empty DataFrame
Columns: [order_id, order_item_id, price, customer_id, order_status, order_date, delivery_date, estimated_delivery_date, product_id, product_category]
Index: []

In [17]:
# Indentify duplicate order_id.
dup_count=orderlevel['order_id'].value_counts()
dup_id=dup_count[dup_count>1].index
dup_id

Index(['8272b63d03f5f79c56e9e4120aec44ef', '1b15974a0141d54e36626dca3fdc731a',
       'ab14fdcfbe524636d65ee38360e22ce8', '428a2f660dc84138d969ccd69a0ab6d5',
       '9ef13efd6949e4573a18964dd1bbe7f5', '73c8ab38f07dc94389065f7eba4f297a',
       '9bdc4d4c71aa1de4606060929dee888c', '37ee401157a3a0b28c9c6d0ed8c3b24b',
       'c05d6a79e55da72ca780ce90364abed9', '637617b3ffe9e2f7a2411243829226d0',
       ...
       'ff98857a36b901baaa0dc19c6fcf65fe', 'ffa5e4c604dea4f0a59d19cc2322ac19',
       'ba6d7557cefd2d4e8fe232a2f9cddd8c', '0782e07a7692b86e29c3fcec805b3bfc',
       '002c9def9c9b951b1bec6d50753c9891', 'cd6cdd3e527f46113dcab23d5f27c0fe',
       'ffc16cecff8dc037f60458f28d1c1ba5', '001d8f0e34a38c37f7dba2a37d4eba8b',
       'ffd543c2b60842e148a86870dc60e212', 'ffd84ab39cd5e873d8dba24342e65c01'],
      dtype='object', name='order_id', length=9803)

In [18]:
df_dup=orderlevel[orderlevel['order_id'].isin(dup_id)].sort_values(['order_id','order_item_id'])
df_dup

,order_id,order_item_id,price,customer_id,order_status,order_date,delivery_date,estimated_delivery_date,product_id,product_category
9,0008288aa423d2a3f00fcb17cd7d8719,1,49.90,2355af7c75e7c98b43a87b2a7f210dc5,delivered,2018-02-13 22:10:00,2018-02-26 13:55:00,2018-03-06,368c6c730842d78016ad823897a372db,garden_tools
10,0008288aa423d2a3f00fcb17cd7d8719,2,49.90,2355af7c75e7c98b43a87b2a7f210dc5,delivered,2018-02-13 22:10:00,2018-02-26 13:55:00,2018-03-06,368c6c730842d78016ad823897a372db,garden_tools
56271,00143d0f86d6fbd9f9b38ab440ac16f5,1,21.33,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:00,2017-10-27 18:43:00,2017-11-06,e95ee6822b66ac6058e2e4aff656071a,sports_leisure
56272,00143d0f86d6fbd9f9b38ab440ac16f5,2,21.33,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:00,2017-10-27 18:43:00,2017-11-06,e95ee6822b66ac6058e2e4aff656071a,sports_leisure
56273,00143d0f86d6fbd9f9b38ab440ac16f5,3,21.33,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:00,2017-10-27 18:43:00,2017-11-06,e95ee6822b66ac6058e2e4aff656071a,sports_leisure
...,...,...,...,...,...,...,...,...,...,...
112648,fff8287bbae429a99bb7e8c21d151c41,2,180.00,6c1e92a209dbf868706caa831090941e,delivered,2018-03-17 12:11:00,2018-04-07 10:07:00,2018-04-19,bee2e070c39f3dd2f6883a17a5f0da45,computers_accessories
56246,fffb9224b6fc7c43ebb0904318b10b5f,1,55.00,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-11-17 19:41:00,2017-11-27,43423cdffde7fda63d0414ed38c11a73,watches_gifts
56247,fffb9224b6fc7c43ebb0904318b10b5f,2,55.00,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-11-17 19:41:00,2017-11-27,43423cdffde7fda63d0414ed38c11a73,watches_gifts
56248,fffb9224b6fc7c43ebb0904318b10b5f,3,55.00,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-11-17 19:41:00,2017-11-27,43423cdffde7fda63d0414ed38c11a73,watches_gifts
56249,fffb9224b6fc7c43ebb0904318b10b5f,4,55.00,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-11-17 19:41:00,2017-11-27,43423cdffde7fda63d0414ed38c11a73,watches_gifts

#### Conclution
- Many customer have bought same product more than one on same day, so it is not duplicate row.

In [19]:
orderlevel.groupby(['order_id','product_id']).size().value_counts()

1     95337
2      5382
3       953
4       390
6       172
5       168
10        5
7         4
20        2
8         2
15        2
12        2
9         2
14        2
13        1
11        1
Name: count, dtype: int64

 ###

 # send to SQL

In [20]:
orderlevel.to_sql(
    name='order_level',
    con=engine,
    if_exists='replace',
    index=False
)

650

### customer_level table

In [21]:
query='''with purchase_spent as(
    select order_id,count(order_id)as quantity,sum(price)as spent_price
	from order_item
	group by 1)

select c.customer_id,c.customer_unique_id,c.customer_city,c.customer_state,
       o.order_status,
       p.quantity,p.spent_price
from customers c
left join orders o on c.customer_id=o.customer_id
left join purchase_spent p on o.order_id=p.order_id'''

In [22]:
df=pd.read_sql_query('''with purchase_spent as(
    select order_id,count(order_id)as quantity,sum(price)as spent_price
	from order_item
	group by 1)

select c.customer_id,c.customer_unique_id,c.customer_city,c.customer_state,
       o.order_status,
       p.quantity,p.spent_price
from customers c
left join orders o on c.customer_id=o.customer_id
left join purchase_spent p on o.order_id=p.order_id''',engine)

In [23]:
df['spent_price']=df['spent_price'].round(2)
df['quantity']=df['quantity'].round(0)
display(df)

,customer_id,customer_unique_id,customer_city,customer_state,order_status,quantity,spent_price
0,d0349571985dc0a748ecdd1b6bf25750,527acd5ee1b69a0edddde8fe512007d9,curitiba,PR,delivered,1.0,177.99
1,8fb17055fd54b0e086d5320642721a88,c667c7454243251d3210c6c54a97c482,janauba,MG,delivered,3.0,345.00
2,885aa5f046631ec02ead6b2bea798a92,359a78f03d3fa44893db34ed3564c7ef,campinas,SP,delivered,1.0,89.49
3,3172fe335c9b335ce749eda3b7c73bd3,9e89d2232df792cde636a47212a9f2bb,rio de janeiro,RJ,delivered,1.0,109.90
4,dac766eabb1289d59cb88e34b1489db1,f9721131784ad9d58ba9278236b37845,sao paulo,SP,delivered,1.0,237.00
...,...,...,...,...,...,...,...
99436,8fa9f17f7cc7af41d068b9b3f8df51e8,5105b52fa696cbca4cd3ddade05149fd,abre campo,MG,canceled,NaN,NaN
99437,bffd28b4af20bc7b1a477fe80e190c77,20763743ec53eec3a9949781bf459e6e,barra velha,SC,unavailable,NaN,NaN
99438,e016de14d2abd37825c4c485cd780b74,e7bb82dae3998954497289418e677dc2,sao gabriel,RS,canceled,NaN,NaN
99439,a5569eafa093045938b448b5f802032d,5bdff994fa115621df0b714401ec5db4,jau,SP,unavailable,NaN,NaN
99440,0c98695352c85d7b6f28a78dcbaff914,f941b66064e2381bd2ebf70aab0c9a33,belo horizonte,MG,unavailable,NaN,NaN

In [24]:
df.describe()

           quantity   spent_price
count  98666.000000  98666.000000
mean       1.141731    137.754076
std        0.538452    210.645145
min        1.000000      0.850000
25%        1.000000     45.900000
50%        1.000000     86.900000
75%        1.000000    149.900000
max       21.000000  13440.000000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         99441 non-null  object
 1   customer_unique_id  99441 non-null  object
 2   customer_city       99441 non-null  object
 3   customer_state      99441 non-null  object
 4   order_status        99441 non-null  object
 5   quantity            98666 non-null  float64
 6   spent_price         98666 non-null  float64
dtypes: float64(2), object(5)
memory usage: 5.3+ MB

In [26]:
df.isnull().sum()

customer_id             0
customer_unique_id      0
customer_city           0
customer_state          0
order_status            0
quantity              775
spent_price           775
dtype: int64

## Null Handling

In [27]:
df_nan=df[df.isnull().any(axis=1)]

df_nan

,customer_id,customer_unique_id,customer_city,customer_state,order_status,quantity,spent_price
24938,60ff6e09a676bfa797f0ae3f1282ce4d,5554446bdf14acb1a4ea581d2dcecef7,volta redonda,RJ,unavailable,NaN,NaN
24939,5f2d32c9dc38e07a3f364d00b94ff674,94c0cc1d2ff6fbba79af9a5769d2b18d,londrina,PR,unavailable,NaN,NaN
24940,9da570dd0f573074ad3458b7ba281a62,b24333c20b1082ee734cd5c25c2991b4,pocos de caldas,MG,unavailable,NaN,NaN
24941,bf6418c67d6b29aada7d4a9a0cfb3e09,2a80d0e64a7056796f27b4f0cb909182,balneario pinhal,RS,unavailable,NaN,NaN
24942,489a3ed6905c005864a69d534cba1aca,5dded311dc99f60b9ed5361b76a7bf82,aracaju,SE,unavailable,NaN,NaN
...,...,...,...,...,...,...,...
99436,8fa9f17f7cc7af41d068b9b3f8df51e8,5105b52fa696cbca4cd3ddade05149fd,abre campo,MG,canceled,NaN,NaN
99437,bffd28b4af20bc7b1a477fe80e190c77,20763743ec53eec3a9949781bf459e6e,barra velha,SC,unavailable,NaN,NaN
99438,e016de14d2abd37825c4c485cd780b74,e7bb82dae3998954497289418e677dc2,sao gabriel,RS,canceled,NaN,NaN
99439,a5569eafa093045938b448b5f802032d,5bdff994fa115621df0b714401ec5db4,jau,SP,unavailable,NaN,NaN
99440,0c98695352c85d7b6f28a78dcbaff914,f941b66064e2381bd2ebf70aab0c9a33,belo horizonte,MG,unavailable,NaN,NaN

In [28]:
df_nan1=df_nan[
(df_nan['order_status']=='canceled') |
(df_nan['order_status']=='unavailable')
]
df_nan1

,customer_id,customer_unique_id,customer_city,customer_state,order_status,quantity,spent_price
24938,60ff6e09a676bfa797f0ae3f1282ce4d,5554446bdf14acb1a4ea581d2dcecef7,volta redonda,RJ,unavailable,NaN,NaN
24939,5f2d32c9dc38e07a3f364d00b94ff674,94c0cc1d2ff6fbba79af9a5769d2b18d,londrina,PR,unavailable,NaN,NaN
24940,9da570dd0f573074ad3458b7ba281a62,b24333c20b1082ee734cd5c25c2991b4,pocos de caldas,MG,unavailable,NaN,NaN
24941,bf6418c67d6b29aada7d4a9a0cfb3e09,2a80d0e64a7056796f27b4f0cb909182,balneario pinhal,RS,unavailable,NaN,NaN
24942,489a3ed6905c005864a69d534cba1aca,5dded311dc99f60b9ed5361b76a7bf82,aracaju,SE,unavailable,NaN,NaN
...,...,...,...,...,...,...,...
99436,8fa9f17f7cc7af41d068b9b3f8df51e8,5105b52fa696cbca4cd3ddade05149fd,abre campo,MG,canceled,NaN,NaN
99437,bffd28b4af20bc7b1a477fe80e190c77,20763743ec53eec3a9949781bf459e6e,barra velha,SC,unavailable,NaN,NaN
99438,e016de14d2abd37825c4c485cd780b74,e7bb82dae3998954497289418e677dc2,sao gabriel,RS,canceled,NaN,NaN
99439,a5569eafa093045938b448b5f802032d,5bdff994fa115621df0b714401ec5db4,jau,SP,unavailable,NaN,NaN
99440,0c98695352c85d7b6f28a78dcbaff914,f941b66064e2381bd2ebf70aab0c9a33,belo horizonte,MG,unavailable,NaN,NaN

In [29]:
df.loc[
          (df['quantity'].isna()) &
           (df['spent_price'].isna()),
   ['quantity','spent_price']
]=0
df

,customer_id,customer_unique_id,customer_city,customer_state,order_status,quantity,spent_price
0,d0349571985dc0a748ecdd1b6bf25750,527acd5ee1b69a0edddde8fe512007d9,curitiba,PR,delivered,1.0,177.99
1,8fb17055fd54b0e086d5320642721a88,c667c7454243251d3210c6c54a97c482,janauba,MG,delivered,3.0,345.00
2,885aa5f046631ec02ead6b2bea798a92,359a78f03d3fa44893db34ed3564c7ef,campinas,SP,delivered,1.0,89.49
3,3172fe335c9b335ce749eda3b7c73bd3,9e89d2232df792cde636a47212a9f2bb,rio de janeiro,RJ,delivered,1.0,109.90
4,dac766eabb1289d59cb88e34b1489db1,f9721131784ad9d58ba9278236b37845,sao paulo,SP,delivered,1.0,237.00
...,...,...,...,...,...,...,...
99436,8fa9f17f7cc7af41d068b9b3f8df51e8,5105b52fa696cbca4cd3ddade05149fd,abre campo,MG,canceled,0.0,0.00
99437,bffd28b4af20bc7b1a477fe80e190c77,20763743ec53eec3a9949781bf459e6e,barra velha,SC,unavailable,0.0,0.00
99438,e016de14d2abd37825c4c485cd780b74,e7bb82dae3998954497289418e677dc2,sao gabriel,RS,canceled,0.0,0.00
99439,a5569eafa093045938b448b5f802032d,5bdff994fa115621df0b714401ec5db4,jau,SP,unavailable,0.0,0.00
99440,0c98695352c85d7b6f28a78dcbaff914,f941b66064e2381bd2ebf70aab0c9a33,belo horizonte,MG,unavailable,0.0,0.00

## Load in PostgreSQL

In [30]:
df.to_sql(
    name='customer_level',
    con=engine,
    if_exists='replace',
    index= False
)

441

## Product_level data load from pgadmin

In [31]:
query="""with order_product as
  (select product_id,order_id,
        round(sum(price)::numeric,2)as product_price
  from order_item
  group by 1,2),

review_product as(
     select o.order_id,o.product_id,r.review_score
	 from order_item o
	  join order_review r on r.order_id=o.order_id)

select o.product_id,o.order_id,o.product_price,
       r.review_score,
	   p.product_category
from order_product o
left join review_product r on o.order_id=r.order_id
 join products p on o.product_id=p.product_id;
       """

In [32]:
df_p=pd.read_sql_query('''with order_product as
  (select product_id,order_id,
        round(sum(price)::numeric,2)as product_price
  from order_item
  group by 1,2),

review_product as(
     select o.order_id,o.product_id,r.review_score
	 from order_item o
	  join order_review r on r.order_id=o.order_id)

select o.product_id,o.order_id,o.product_price,
       r.review_score,
	   p.product_category
from order_product o
left join review_product r on o.order_id=r.order_id
 join products p on o.product_id=p.product_id;
       ''',engine)

In [33]:
df_p

,product_id,order_id,product_price,review_score,product_category
0,00066f42aeeb9f3007548bb9d3f33c38,f30149f4a8882a08895b6a242aa0d612,101.65,5.0,perfumery
1,0009406fd7479715e4bef61dd91f2462,0bf736fd0fd5169d60de3699fcbcf986,229.00,1.0,bed_bath_table
2,000b8f95fcb9e0096488278317764d19,3aba44d8e554ab4bb8c09f6f78032ca8,58.90,5.0,housewares
3,000b8f95fcb9e0096488278317764d19,6f0dfb5b5398b271cc6bbd9ee263530e,58.90,NaN,housewares
4,0011c512eb256aa0dbbb544d8dffcf6e,bb9552306cf6879fde49f4ba3bd94299,52.00,1.0,auto
...,...,...,...,...,...
119623,fff6177642830a9a94a0f2cba5e476d1,e91d77b27ccd3bac6b23a34a44ae3db1,109.99,5.0,cool_stuff
119624,fff9553ac224cec9d15d49f5a263411f,df3a7600e4fd0a2c595fa7ad6e2e622e,32.00,5.0,fashion_bags_accessories
119625,fffdb2d0ec8d6a61f0a0a0db3f25b441,2878b4e373a9556df9aa1708a4e5c3c8,34.99,5.0,computers_accessories
119626,fffdb2d0ec8d6a61f0a0a0db3f25b441,dd38c566a34ff9deb93ff05d7bd6d0aa,34.99,5.0,computers_accessories
119627,fffe9eeff12fcbd74a2f2b007dde0c58,fbf3da6fe82010412982890b0c57e532,249.99,4.0,toys

In [34]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119628 entries, 0 to 119627
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   product_id        119628 non-null  object
 1   order_id          119628 non-null  object
 2   product_price     119628 non-null  float64
 3   review_score      109076 non-null  float64
 4   product_category  117950 non-null  object
dtypes: float64(2), object(3)
memory usage: 4.6+ MB

In [35]:
df_p.isnull().sum()

product_id              0
order_id                0
product_price           0
review_score        10552
product_category     1678
dtype: int64

In [36]:
null_r=df_p[df_p.isnull().any(axis=1)]
null_r

,product_id,order_id,product_price,review_score,product_category
3,000b8f95fcb9e0096488278317764d19,6f0dfb5b5398b271cc6bbd9ee263530e,58.90,NaN,housewares
15,001b72dfd63e9833e8c02742adf472e3,70ed857e24fd6bf1e25a9bc791a2f6b9,34.99,NaN,furniture_decor
30,002159fe700ed3521f46cfcf6e941c76,482b0898624ebab18e90d224126c98a8,199.70,NaN,fashion_shoes
70,0067f97995b0c3a86739734dc87ee6b6,a4d63c74eb133a700461000c2e8df158,79.00,NaN,fashion_bags_accessories
98,00917855135d67fb060dcd81863166a4,16bd72af325ac043d6194e490e2f0f06,39.90,NaN,computers_accessories
...,...,...,...,...,...
119578,ffc88104d219c1b767d566fd93653dd2,8682a030870edcce6a8b8299b68aa4d6,39.90,NaN,housewares
119581,ffc9caf33e2d1e9f44e3e06da19085f7,14d64059935405be1dc46f30f7a123ac,199.89,NaN,health_beauty
119584,ffc9caf33e2d1e9f44e3e06da19085f7,5ce08134a7e1f35b93fe223acef734bf,224.00,NaN,health_beauty
119612,ffedbd68fa6f44e788ff6c2db8094715,ae22bdc244206a1adac2358b09ad3ab0,40.00,NaN,books_technical
119613,ffedbd68fa6f44e788ff6c2db8094715,dac3092fa896a585ef8cfe91762294e5,40.00,NaN,books_technical

In [37]:
df_p=df_p.dropna()

In [38]:
df_p['review_score'].unique()

array([5., 1., 3., 4., 2.])

In [39]:
map_review={
    1:'very bad',
    2:'bad',
    3:'average',
    4:'good',
    5:'very good'
}

df_p['review_label']=df_p['review_score'].map(map_review)
df_p

C:\Users\hp\AppData\Local\Temp\ipykernel_16492\1565276208.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['review_label']=df_p['review_score'].map(map_review)

,product_id,order_id,product_price,review_score,product_category,review_label
0,00066f42aeeb9f3007548bb9d3f33c38,f30149f4a8882a08895b6a242aa0d612,101.65,5.0,perfumery,very good
1,0009406fd7479715e4bef61dd91f2462,0bf736fd0fd5169d60de3699fcbcf986,229.00,1.0,bed_bath_table,very bad
2,000b8f95fcb9e0096488278317764d19,3aba44d8e554ab4bb8c09f6f78032ca8,58.90,5.0,housewares,very good
4,0011c512eb256aa0dbbb544d8dffcf6e,bb9552306cf6879fde49f4ba3bd94299,52.00,1.0,auto,very bad
5,0011c512eb256aa0dbbb544d8dffcf6e,bb9552306cf6879fde49f4ba3bd94299,52.00,1.0,auto,very bad
...,...,...,...,...,...,...
119623,fff6177642830a9a94a0f2cba5e476d1,e91d77b27ccd3bac6b23a34a44ae3db1,109.99,5.0,cool_stuff,very good
119624,fff9553ac224cec9d15d49f5a263411f,df3a7600e4fd0a2c595fa7ad6e2e622e,32.00,5.0,fashion_bags_accessories,very good
119625,fffdb2d0ec8d6a61f0a0a0db3f25b441,2878b4e373a9556df9aa1708a4e5c3c8,34.99,5.0,computers_accessories,very good
119626,fffdb2d0ec8d6a61f0a0a0db3f25b441,dd38c566a34ff9deb93ff05d7bd6d0aa,34.99,5.0,computers_accessories,very good
119627,fffe9eeff12fcbd74a2f2b007dde0c58,fbf3da6fe82010412982890b0c57e532,249.99,4.0,toys,good

In [40]:
total_rev= df_p.groupby(['product_id','product_category']).agg({
    'product_price':'sum',
    'review_score':'count'
})

total_rev=total_rev.sort_values(['review_score'],ascending=False)
total_rev

,,product_price,review_score
product_id,product_category,,
99a4788cb24856965c36a24e339b6058,bed_bath_table,46768.66,491
aca2eb7d00ea1a7b8ebd4e68314663af,furniture_decor,46864.90,474
422879e10f46682990de24d770e7f83d,garden_tools,53788.19,463
389d119b48cf3043d311335e499d9c6b,garden_tools,32773.89,392
368c6c730842d78016ad823897a372db,garden_tools,32750.10,361
...,...,...,...
ffd259a48b9b073c942884d0f3659566,fashion_male_clothing,199.00,1
ffd63ee42a5c8cc5a15a1c8e2aa50011,agro_industry_and_commerce,77.00,1
ffd7628b0b0b98ebc549e8e4c54a59af,health_beauty,79.90,1
ffd9ac56db9194a413298faaa03cd176,pet_shop,89.00,1
ffdde3d63e889c9a9f9ec30d82a4c815,toys,1449.00,1

## Load in postgre.

In [41]:
df_p.to_sql(
    name='product_level',
        con=engine,
    if_exists='replace',
    index= False
)

590